/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthRouteRouteImport } from './pages/_auth/route'
import { Route as AuthenticatedIndexRouteImport } from './pages/_authenticated/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './pages/_authenticated/admin/route'
import { Route as AuthLoginIndexRouteImport } from './pages/_auth/login/index'
import { Route as AuthenticatedAdminSettingsIndexRouteImport } from './pages/_authenticated/admin/settings/index'
import { Route as AuthenticatedAdminRolesIndexRouteImport } from './pages/_authenticated/admin/roles/index'
import { Route as AuthenticatedAdminPermissionsIndexRouteImport } from './pages/_authenticated/admin/permissions/index'
import { Route as AuthenticatedAdminOnlineCoursesIndexRouteImport } from './pages/_authenticated/admin/online-courses/index'
import { Route as AuthenticatedAdminLessonsIndexRouteImport } from './pages/_authenticated/admin/lessons/index'
import { Route as AuthenticatedAdminLessonSessionsIndexRouteImport } from './pages/_authenticated/admin/lesson-sessions/index'
import { Route as AuthenticatedAdminGroupsIndexRouteImport } from './pages/_authenticated/admin/groups/index'
import { Route as AuthenticatedAdminCoursesIndexRouteImport } from './pages/_authenticated/admin/courses/index'
import { Route as AuthenticatedAdminCourseSectionsIndexRouteImport } from './pages/_authenticated/admin/course-sections/index'
import { Route as AuthenticatedAdminUserTeachersIndexRouteImport } from './pages/_authenticated/admin/user/teachers/index'
import { Route as AuthenticatedAdminUserStudentsIndexRouteImport } from './pages/_authenticated/admin/user/students/index'
import { Route as AuthenticatedAdminUserParentsIndexRouteImport } from './pages/_authenticated/admin/user/parents/index'
import { Route as AuthenticatedAdminUserAllIndexRouteImport } from './pages/_authenticated/admin/user/all/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_authenticated/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedAdminSettingsIndexRoute =
  AuthenticatedAdminSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRolesIndexRoute =
  AuthenticatedAdminRolesIndexRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPermissionsIndexRoute =
  AuthenticatedAdminPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOnlineCoursesIndexRoute =
  AuthenticatedAdminOnlineCoursesIndexRouteImport.update({
    id: '/online-courses/',
    path: '/online-courses/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLessonsIndexRoute =
  AuthenticatedAdminLessonsIndexRouteImport.update({
    id: '/lessons/',
    path: '/lessons/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLessonSessionsIndexRoute =
  AuthenticatedAdminLessonSessionsIndexRouteImport.update({
    id: '/lesson-sessions/',
    path: '/lesson-sessions/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGroupsIndexRoute =
  AuthenticatedAdminGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCoursesIndexRoute =
  AuthenticatedAdminCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCourseSectionsIndexRoute =
  AuthenticatedAdminCourseSectionsIndexRouteImport.update({
    id: '/course-sections/',
    path: '/course-sections/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUserTeachersIndexRoute =
  AuthenticatedAdminUserTeachersIndexRouteImport.update({
    id: '/user/teachers/',
    path: '/user/teachers/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUserStudentsIndexRoute =
  AuthenticatedAdminUserStudentsIndexRouteImport.update({
    id: '/user/students/',
    path: '/user/students/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUserParentsIndexRoute =
  AuthenticatedAdminUserParentsIndexRouteImport.update({
    id: '/user/parents/',
    path: '/user/parents/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUserAllIndexRoute =
  AuthenticatedAdminUserAllIndexRouteImport.update({
    id: '/user/all/',
    path: '/user/all/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/admin/course-sections': typeof AuthenticatedAdminCourseSectionsIndexRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesIndexRoute
  '/admin/groups': typeof AuthenticatedAdminGroupsIndexRoute
  '/admin/lesson-sessions': typeof AuthenticatedAdminLessonSessionsIndexRoute
  '/admin/lessons': typeof AuthenticatedAdminLessonsIndexRoute
  '/admin/online-courses': typeof AuthenticatedAdminOnlineCoursesIndexRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsIndexRoute
  '/admin/roles': typeof AuthenticatedAdminRolesIndexRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsIndexRoute
  '/admin/user/all': typeof AuthenticatedAdminUserAllIndexRoute
  '/admin/user/parents': typeof AuthenticatedAdminUserParentsIndexRoute
  '/admin/user/students': typeof AuthenticatedAdminUserStudentsIndexRoute
  '/admin/user/teachers': typeof AuthenticatedAdminUserTeachersIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/admin/course-sections': typeof AuthenticatedAdminCourseSectionsIndexRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesIndexRoute
  '/admin/groups': typeof AuthenticatedAdminGroupsIndexRoute
  '/admin/lesson-sessions': typeof AuthenticatedAdminLessonSessionsIndexRoute
  '/admin/lessons': typeof AuthenticatedAdminLessonsIndexRoute
  '/admin/online-courses': typeof AuthenticatedAdminOnlineCoursesIndexRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsIndexRoute
  '/admin/roles': typeof AuthenticatedAdminRolesIndexRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsIndexRoute
  '/admin/user/all': typeof AuthenticatedAdminUserAllIndexRoute
  '/admin/user/parents': typeof AuthenticatedAdminUserParentsIndexRoute
  '/admin/user/students': typeof AuthenticatedAdminUserStudentsIndexRoute
  '/admin/user/teachers': typeof AuthenticatedAdminUserTeachersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_authenticated/admin/course-sections/': typeof AuthenticatedAdminCourseSectionsIndexRoute
  '/_authenticated/admin/courses/': typeof AuthenticatedAdminCoursesIndexRoute
  '/_authenticated/admin/groups/': typeof AuthenticatedAdminGroupsIndexRoute
  '/_authenticated/admin/lesson-sessions/': typeof AuthenticatedAdminLessonSessionsIndexRoute
  '/_authenticated/admin/lessons/': typeof AuthenticatedAdminLessonsIndexRoute
  '/_authenticated/admin/online-courses/': typeof AuthenticatedAdminOnlineCoursesIndexRoute
  '/_authenticated/admin/permissions/': typeof AuthenticatedAdminPermissionsIndexRoute
  '/_authenticated/admin/roles/': typeof AuthenticatedAdminRolesIndexRoute
  '/_authenticated/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/_authenticated/admin/user/all/': typeof AuthenticatedAdminUserAllIndexRoute
  '/_authenticated/admin/user/parents/': typeof AuthenticatedAdminUserParentsIndexRoute
  '/_authenticated/admin/user/students/': typeof AuthenticatedAdminUserStudentsIndexRoute
  '/_authenticated/admin/user/teachers/': typeof AuthenticatedAdminUserTeachersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/'
    | '/login'
    | '/admin/course-sections'
    | '/admin/courses'
    | '/admin/groups'
    | '/admin/lesson-sessions'
    | '/admin/lessons'
    | '/admin/online-courses'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/user/all'
    | '/admin/user/parents'
    | '/admin/user/students'
    | '/admin/user/teachers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/'
    | '/login'
    | '/admin/course-sections'
    | '/admin/courses'
    | '/admin/groups'
    | '/admin/lesson-sessions'
    | '/admin/lessons'
    | '/admin/online-courses'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/user/all'
    | '/admin/user/parents'
    | '/admin/user/students'
    | '/admin/user/teachers'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated/admin'
    | '/_authenticated/'
    | '/_auth/login/'
    | '/_authenticated/admin/course-sections/'
    | '/_authenticated/admin/courses/'
    | '/_authenticated/admin/groups/'
    | '/_authenticated/admin/lesson-sessions/'
    | '/_authenticated/admin/lessons/'
    | '/_authenticated/admin/online-courses/'
    | '/_authenticated/admin/permissions/'
    | '/_authenticated/admin/roles/'
    | '/_authenticated/admin/settings/'
    | '/_authenticated/admin/user/all/'
    | '/_authenticated/admin/user/parents/'
    | '/_authenticated/admin/user/students/'
    | '/_authenticated/admin/user/teachers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/admin/settings/': {
      id: '/_authenticated/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/roles/': {
      id: '/_authenticated/admin/roles/'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/permissions/': {
      id: '/_authenticated/admin/permissions/'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/online-courses/': {
      id: '/_authenticated/admin/online-courses/'
      path: '/online-courses'
      fullPath: '/admin/online-courses'
      preLoaderRoute: typeof AuthenticatedAdminOnlineCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/lessons/': {
      id: '/_authenticated/admin/lessons/'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AuthenticatedAdminLessonsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/lesson-sessions/': {
      id: '/_authenticated/admin/lesson-sessions/'
      path: '/lesson-sessions'
      fullPath: '/admin/lesson-sessions'
      preLoaderRoute: typeof AuthenticatedAdminLessonSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/groups/': {
      id: '/_authenticated/admin/groups/'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AuthenticatedAdminGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/courses/': {
      id: '/_authenticated/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/course-sections/': {
      id: '/_authenticated/admin/course-sections/'
      path: '/course-sections'
      fullPath: '/admin/course-sections'
      preLoaderRoute: typeof AuthenticatedAdminCourseSectionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/user/teachers/': {
      id: '/_authenticated/admin/user/teachers/'
      path: '/user/teachers'
      fullPath: '/admin/user/teachers'
      preLoaderRoute: typeof AuthenticatedAdminUserTeachersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/user/students/': {
      id: '/_authenticated/admin/user/students/'
      path: '/user/students'
      fullPath: '/admin/user/students'
      preLoaderRoute: typeof AuthenticatedAdminUserStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/user/parents/': {
      id: '/_authenticated/admin/user/parents/'
      path: '/user/parents'
      fullPath: '/admin/user/parents'
      preLoaderRoute: typeof AuthenticatedAdminUserParentsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/user/all/': {
      id: '/_authenticated/admin/user/all/'
      path: '/user/all'
      fullPath: '/admin/user/all'
      preLoaderRoute: typeof AuthenticatedAdminUserAllIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCourseSectionsIndexRoute: typeof AuthenticatedAdminCourseSectionsIndexRoute
  AuthenticatedAdminCoursesIndexRoute: typeof AuthenticatedAdminCoursesIndexRoute
  AuthenticatedAdminGroupsIndexRoute: typeof AuthenticatedAdminGroupsIndexRoute
  AuthenticatedAdminLessonSessionsIndexRoute: typeof AuthenticatedAdminLessonSessionsIndexRoute
  AuthenticatedAdminLessonsIndexRoute: typeof AuthenticatedAdminLessonsIndexRoute
  AuthenticatedAdminOnlineCoursesIndexRoute: typeof AuthenticatedAdminOnlineCoursesIndexRoute
  AuthenticatedAdminPermissionsIndexRoute: typeof AuthenticatedAdminPermissionsIndexRoute
  AuthenticatedAdminRolesIndexRoute: typeof AuthenticatedAdminRolesIndexRoute
  AuthenticatedAdminSettingsIndexRoute: typeof AuthenticatedAdminSettingsIndexRoute
  AuthenticatedAdminUserAllIndexRoute: typeof AuthenticatedAdminUserAllIndexRoute
  AuthenticatedAdminUserParentsIndexRoute: typeof AuthenticatedAdminUserParentsIndexRoute
  AuthenticatedAdminUserStudentsIndexRoute: typeof AuthenticatedAdminUserStudentsIndexRoute
  AuthenticatedAdminUserTeachersIndexRoute: typeof AuthenticatedAdminUserTeachersIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCourseSectionsIndexRoute:
      AuthenticatedAdminCourseSectionsIndexRoute,
    AuthenticatedAdminCoursesIndexRoute: AuthenticatedAdminCoursesIndexRoute,
    AuthenticatedAdminGroupsIndexRoute: AuthenticatedAdminGroupsIndexRoute,
    AuthenticatedAdminLessonSessionsIndexRoute:
      AuthenticatedAdminLessonSessionsIndexRoute,
    AuthenticatedAdminLessonsIndexRoute: AuthenticatedAdminLessonsIndexRoute,
    AuthenticatedAdminOnlineCoursesIndexRoute:
      AuthenticatedAdminOnlineCoursesIndexRoute,
    AuthenticatedAdminPermissionsIndexRoute:
      AuthenticatedAdminPermissionsIndexRoute,
    AuthenticatedAdminRolesIndexRoute: AuthenticatedAdminRolesIndexRoute,
    AuthenticatedAdminSettingsIndexRoute: AuthenticatedAdminSettingsIndexRoute,
    AuthenticatedAdminUserAllIndexRoute: AuthenticatedAdminUserAllIndexRoute,
    AuthenticatedAdminUserParentsIndexRoute:
      AuthenticatedAdminUserParentsIndexRoute,
    AuthenticatedAdminUserStudentsIndexRoute:
      AuthenticatedAdminUserStudentsIndexRoute,
    AuthenticatedAdminUserTeachersIndexRoute:
      AuthenticatedAdminUserTeachersIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
