/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthenticatedRouteRouteImport } from './pages/_authenticated/route'
import { Route as AuthRouteRouteImport } from './pages/_auth/route'
import { Route as AuthenticatedIndexRouteImport } from './pages/_authenticated/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './pages/_authenticated/settings/index'
import { Route as AuthenticatedRolesIndexRouteImport } from './pages/_authenticated/roles/index'
import { Route as AuthenticatedPermissionsIndexRouteImport } from './pages/_authenticated/permissions/index'
import { Route as AuthenticatedOnlineCoursesIndexRouteImport } from './pages/_authenticated/online-courses/index'
import { Route as AuthenticatedLessonsIndexRouteImport } from './pages/_authenticated/lessons/index'
import { Route as AuthenticatedLessonSessionsIndexRouteImport } from './pages/_authenticated/lesson-sessions/index'
import { Route as AuthenticatedGroupsIndexRouteImport } from './pages/_authenticated/groups/index'
import { Route as AuthenticatedCoursesIndexRouteImport } from './pages/_authenticated/courses/index'
import { Route as AuthenticatedCourseSectionsIndexRouteImport } from './pages/_authenticated/course-sections/index'
import { Route as AuthLoginIndexRouteImport } from './pages/_auth/login/index'
import { Route as AuthenticatedUserTeachersIndexRouteImport } from './pages/_authenticated/user/teachers/index'
import { Route as AuthenticatedUserStudentsIndexRouteImport } from './pages/_authenticated/user/students/index'
import { Route as AuthenticatedUserParentsIndexRouteImport } from './pages/_authenticated/user/parents/index'
import { Route as AuthenticatedUserAllIndexRouteImport } from './pages/_authenticated/user/all/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissionsIndexRoute =
  AuthenticatedPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnlineCoursesIndexRoute =
  AuthenticatedOnlineCoursesIndexRouteImport.update({
    id: '/online-courses/',
    path: '/online-courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLessonsIndexRoute =
  AuthenticatedLessonsIndexRouteImport.update({
    id: '/lessons/',
    path: '/lessons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLessonSessionsIndexRoute =
  AuthenticatedLessonSessionsIndexRouteImport.update({
    id: '/lesson-sessions/',
    path: '/lesson-sessions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesIndexRoute =
  AuthenticatedCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCourseSectionsIndexRoute =
  AuthenticatedCourseSectionsIndexRouteImport.update({
    id: '/course-sections/',
    path: '/course-sections/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedUserTeachersIndexRoute =
  AuthenticatedUserTeachersIndexRouteImport.update({
    id: '/user/teachers/',
    path: '/user/teachers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserStudentsIndexRoute =
  AuthenticatedUserStudentsIndexRouteImport.update({
    id: '/user/students/',
    path: '/user/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserParentsIndexRoute =
  AuthenticatedUserParentsIndexRouteImport.update({
    id: '/user/parents/',
    path: '/user/parents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserAllIndexRoute =
  AuthenticatedUserAllIndexRouteImport.update({
    id: '/user/all/',
    path: '/user/all/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/course-sections': typeof AuthenticatedCourseSectionsIndexRoute
  '/courses': typeof AuthenticatedCoursesIndexRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/lesson-sessions': typeof AuthenticatedLessonSessionsIndexRoute
  '/lessons': typeof AuthenticatedLessonsIndexRoute
  '/online-courses': typeof AuthenticatedOnlineCoursesIndexRoute
  '/permissions': typeof AuthenticatedPermissionsIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/user/all': typeof AuthenticatedUserAllIndexRoute
  '/user/parents': typeof AuthenticatedUserParentsIndexRoute
  '/user/students': typeof AuthenticatedUserStudentsIndexRoute
  '/user/teachers': typeof AuthenticatedUserTeachersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/course-sections': typeof AuthenticatedCourseSectionsIndexRoute
  '/courses': typeof AuthenticatedCoursesIndexRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/lesson-sessions': typeof AuthenticatedLessonSessionsIndexRoute
  '/lessons': typeof AuthenticatedLessonsIndexRoute
  '/online-courses': typeof AuthenticatedOnlineCoursesIndexRoute
  '/permissions': typeof AuthenticatedPermissionsIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/user/all': typeof AuthenticatedUserAllIndexRoute
  '/user/parents': typeof AuthenticatedUserParentsIndexRoute
  '/user/students': typeof AuthenticatedUserStudentsIndexRoute
  '/user/teachers': typeof AuthenticatedUserTeachersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_authenticated/course-sections/': typeof AuthenticatedCourseSectionsIndexRoute
  '/_authenticated/courses/': typeof AuthenticatedCoursesIndexRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/_authenticated/lesson-sessions/': typeof AuthenticatedLessonSessionsIndexRoute
  '/_authenticated/lessons/': typeof AuthenticatedLessonsIndexRoute
  '/_authenticated/online-courses/': typeof AuthenticatedOnlineCoursesIndexRoute
  '/_authenticated/permissions/': typeof AuthenticatedPermissionsIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/user/all/': typeof AuthenticatedUserAllIndexRoute
  '/_authenticated/user/parents/': typeof AuthenticatedUserParentsIndexRoute
  '/_authenticated/user/students/': typeof AuthenticatedUserStudentsIndexRoute
  '/_authenticated/user/teachers/': typeof AuthenticatedUserTeachersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/course-sections'
    | '/courses'
    | '/groups'
    | '/lesson-sessions'
    | '/lessons'
    | '/online-courses'
    | '/permissions'
    | '/roles'
    | '/settings'
    | '/user/all'
    | '/user/parents'
    | '/user/students'
    | '/user/teachers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/course-sections'
    | '/courses'
    | '/groups'
    | '/lesson-sessions'
    | '/lessons'
    | '/online-courses'
    | '/permissions'
    | '/roles'
    | '/settings'
    | '/user/all'
    | '/user/parents'
    | '/user/students'
    | '/user/teachers'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_authenticated/'
    | '/_auth/login/'
    | '/_authenticated/course-sections/'
    | '/_authenticated/courses/'
    | '/_authenticated/groups/'
    | '/_authenticated/lesson-sessions/'
    | '/_authenticated/lessons/'
    | '/_authenticated/online-courses/'
    | '/_authenticated/permissions/'
    | '/_authenticated/roles/'
    | '/_authenticated/settings/'
    | '/_authenticated/user/all/'
    | '/_authenticated/user/parents/'
    | '/_authenticated/user/students/'
    | '/_authenticated/user/teachers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions/': {
      id: '/_authenticated/permissions/'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/online-courses/': {
      id: '/_authenticated/online-courses/'
      path: '/online-courses'
      fullPath: '/online-courses'
      preLoaderRoute: typeof AuthenticatedOnlineCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lessons/': {
      id: '/_authenticated/lessons/'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof AuthenticatedLessonsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lesson-sessions/': {
      id: '/_authenticated/lesson-sessions/'
      path: '/lesson-sessions'
      fullPath: '/lesson-sessions'
      preLoaderRoute: typeof AuthenticatedLessonSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/': {
      id: '/_authenticated/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/course-sections/': {
      id: '/_authenticated/course-sections/'
      path: '/course-sections'
      fullPath: '/course-sections'
      preLoaderRoute: typeof AuthenticatedCourseSectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/user/teachers/': {
      id: '/_authenticated/user/teachers/'
      path: '/user/teachers'
      fullPath: '/user/teachers'
      preLoaderRoute: typeof AuthenticatedUserTeachersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/students/': {
      id: '/_authenticated/user/students/'
      path: '/user/students'
      fullPath: '/user/students'
      preLoaderRoute: typeof AuthenticatedUserStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/parents/': {
      id: '/_authenticated/user/parents/'
      path: '/user/parents'
      fullPath: '/user/parents'
      preLoaderRoute: typeof AuthenticatedUserParentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/all/': {
      id: '/_authenticated/user/all/'
      path: '/user/all'
      fullPath: '/user/all'
      preLoaderRoute: typeof AuthenticatedUserAllIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCourseSectionsIndexRoute: typeof AuthenticatedCourseSectionsIndexRoute
  AuthenticatedCoursesIndexRoute: typeof AuthenticatedCoursesIndexRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
  AuthenticatedLessonSessionsIndexRoute: typeof AuthenticatedLessonSessionsIndexRoute
  AuthenticatedLessonsIndexRoute: typeof AuthenticatedLessonsIndexRoute
  AuthenticatedOnlineCoursesIndexRoute: typeof AuthenticatedOnlineCoursesIndexRoute
  AuthenticatedPermissionsIndexRoute: typeof AuthenticatedPermissionsIndexRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedUserAllIndexRoute: typeof AuthenticatedUserAllIndexRoute
  AuthenticatedUserParentsIndexRoute: typeof AuthenticatedUserParentsIndexRoute
  AuthenticatedUserStudentsIndexRoute: typeof AuthenticatedUserStudentsIndexRoute
  AuthenticatedUserTeachersIndexRoute: typeof AuthenticatedUserTeachersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCourseSectionsIndexRoute: AuthenticatedCourseSectionsIndexRoute,
  AuthenticatedCoursesIndexRoute: AuthenticatedCoursesIndexRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
  AuthenticatedLessonSessionsIndexRoute: AuthenticatedLessonSessionsIndexRoute,
  AuthenticatedLessonsIndexRoute: AuthenticatedLessonsIndexRoute,
  AuthenticatedOnlineCoursesIndexRoute: AuthenticatedOnlineCoursesIndexRoute,
  AuthenticatedPermissionsIndexRoute: AuthenticatedPermissionsIndexRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedUserAllIndexRoute: AuthenticatedUserAllIndexRoute,
  AuthenticatedUserParentsIndexRoute: AuthenticatedUserParentsIndexRoute,
  AuthenticatedUserStudentsIndexRoute: AuthenticatedUserStudentsIndexRoute,
  AuthenticatedUserTeachersIndexRoute: AuthenticatedUserTeachersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
